import test from 'node:test';
import assert from 'node:assert/strict';
import { compile, run } from './api.mjs';
const out = source => run(source).output;

test('arithmetic precedence and safe division', () => assert.equal(out('print(2 + 3 * 4, 7 / 2)'), '14 3.5\n'));
test('functions, recursion and entry point', () => assert.equal(out('fn fib(n: Int) -> Int { if n < 2 { return n } return fib(n-1) + fib(n-2) } fn main() { print(fib(10)) }'), '55\n'));
test('short circuit prevents side effects and faults', () => assert.equal(out('var n = 0 fn side() -> Bool { n += 1 return true } print(false && side(), true || side(), n)'), 'false true 0\n'));
test('loop scopes, break and continue', () => assert.equal(out('var s = 0 for n in range(10) { if n == 2 { continue } if n == 5 { break } s += n } print(s)'), '8\n'));
test('while loop', () => assert.equal(out('var n = 3 while n > 0 { print(n) n -= 1 }'), '3\n2\n1\n'));
test('closures capture mutable lexical cells', () => assert.equal(out('fn counter() { var n = 0 return fn() { n += 1 return n } } let c = counter() print(c(), c())'), '1 2\n'));
test('closure locals do not leak across calls', () => assert.equal(out('fn make(n: Int) { return fn(x: Int) { return n + x } } let a = make(2) let b = make(8) print(a(3), b(3))'), '5 11\n'));
test('arrays and bounds checked mutation', () => assert.equal(out('let a = [1,2,3] a[1] = 8 push(a, 4) print(a, len(a))'), '[1, 8, 3, 4] 4\n'));
test('dictionary access and mutation', () => assert.equal(out('let a = {"name": "AION", "v": 1} a.v = 2 print(a.name, a["v"])'), 'AION 2\n'));
test('string interpolation and literal braces', () => assert.equal(out('let name = "Reza" print("Hello, {name}! {{ok}} {2+3}")'), 'Hello, Reza! {ok} 5\n'));
test('Unicode identifiers', () => assert.equal(out('let عدد = 42 print(عدد)'), '42\n'));
test('higher order functions', () => assert.equal(out('fn twice(f, x) { return f(f(x)) } print(twice(fn(n) { return n*2 }, 3))'), '12\n'));
test('known type mismatch rejected', () => assert.throws(() => compile('let n: Int = "x"'), /Int.*String|String.*Int/));
test('immutable binding cannot be reassigned', () => assert.throws(() => compile('let n = 1 n = 2'), /immutable|let/));
test('unknown identifiers have source diagnostics', () => assert.throws(() => compile('print(missing)'), e => e.code === 'E_NAME' && e.line === 1));
test('break outside loop rejected', () => assert.throws(() => compile('break'), /loop/));
test('return outside function rejected', () => assert.throws(() => compile('return 3'), /function/));
test('boolean conditions enforced', () => assert.throws(() => compile('if 1 { print(1) }'), /Bool/));
test('known function arity checked', () => assert.throws(() => compile('fn f(x: Int) { print(x) } f()'), /argument|arity/));
test('division by zero is a language error', () => assert.throws(() => run('print(1/0)'), e => e.code === 'E_ZERO'));
test('array read bounds checked', () => assert.throws(() => run('let a = [1] print(a[4])'), /bounds/));
test('array writes cannot create holes', () => assert.throws(() => run('let a = [1] a[3] = 7'), /bounds/));
test('instruction budget stops infinite loops', () => assert.throws(() => run('while true {}', {fuel:1000}), e => e.code === 'E_FUEL'));
test('call depth limit gives language diagnostics', () => assert.throws(() => run('fn f() { return f() } f()', {maxDepth:30}), e => e.code === 'E_DEPTH'));
test('string and number arithmetic do not coerce', () => assert.throws(() => compile('print("4" + 2)'), /type|String|number/));
test('unterminated comments rejected', () => assert.throws(() => compile('/* nope'), /Unterminated/));
test('empty program runs without output', () => assert.equal(out(''), ''));
