export const lessons = [
  { id: 'hello', title: '۱. اولین برنامه', explanation: 'print مقدارها را در خروجی نمایش می‌دهد. نام‌ها و متن‌ها می‌توانند فارسی باشند.', source: 'let نام = "دنیا"\nprint("سلام {نام}!")', output: 'سلام دنیا!\n', exercise: 'نام را به نام خودت تغییر بده.' },
  { id: 'variables', title: '۲. متغیر و نوع', explanation: 'let برای اتصال ثابت و var برای اتصال قابل تغییر است. Int عدد صحیح و String متن است. نوعِ مشخص‌شده هنگام اجرا نیز بررسی می‌شود.', source: 'var امتیاز: Int = 10\nامتیاز += 5\nprint(امتیاز)', output: '15\n', exercise: 'امتیاز را دو برابر کن و خروجی ۳۰ بگیر.' },
  { id: 'conditions', title: '۳. شرط‌ها', explanation: 'شرط if باید Bool باشد. else مسیر دیگر را اجرا می‌کند. && و || ارزیابی کوتاه دارند.', source: 'let score = 80\nif score >= 60 {\n  print("قبول")\n} else {\n  print("دوباره تلاش کن")\n}', output: 'قبول\n', exercise: 'برای نمرهٔ زیر ۶۰ خروجی مسیر else را ببین.' },
  { id: 'loops', title: '۴. حلقه و جمع', explanation: 'range ابتدا را شامل می‌شود و انتها را شامل نمی‌شود. for مقدارهای آرایه را یکی‌یکی می‌گیرد.', source: 'var total = 0\nfor n in range(1, 6) {\n  total += n\n}\nprint(total)', output: '15\n', exercise: 'جمع عددهای ۱ تا ۱۰ را حساب کن؛ جواب ۵۵ است.' },
  { id: 'functions', title: '۵. تابع', explanation: 'پارامترها، خروجی و بدنهٔ تابع با fn تعریف می‌شوند. تابع زیر دو عدد صحیح را جمع می‌کند.', source: 'fn add(a: Int, b: Int) -> Int {\n  return a + b\n}\nprint(add(20, 22))', output: '42\n', exercise: 'تابع square بساز که ۷ را به ۴۹ تبدیل کند.' },
  { id: 'arrays', title: '۶. آرایه و دیکشنری', explanation: 'شمارهٔ اولین خانه صفر است. let آرایه را منجمد نمی‌کند. push عنصر اضافه می‌کند. کلید دیکشنری رشته است.', source: 'let scores: Int[] = [10, 20]\npush(scores, 30)\nlet user = {name: "Ghost", level: 3}\nprint(scores[0], len(scores), user.name)', output: '10 3 Ghost\n', exercise: 'عنصر اول را به ۹۹ تغییر بده. افزودن متن به Int[] را امتحان کن و خطا را بخوان.' },
  { id: 'closures', title: '۷. تابعی که state را حفظ می‌کند', explanation: 'closure به متغیرهای محیط تعریفش دسترسی دارد. هر بار counter را صدا بزنی، یک شمارندهٔ مستقل می‌سازی.', source: 'fn counter(start: Int) {\n  var value = start\n  return fn() {\n    value += 1\n    return value\n  }\n}\nlet next = counter(40)\nprint(next(), next())', output: '41 42\n', exercise: 'دو شمارندهٔ مستقل با شروع‌های صفر و صد بساز.' },
  { id: 'pipeline', title: '۸. پردازش داده', explanation: 'map داده را تبدیل می‌کند، filter انتخاب می‌کند و reduce نتیجه‌ها را جمع می‌کند. ترتیب reduce: آرایه، مقدار اولیه، تابع.', source: 'let squares = map(range(1, 6), fn(n) { return n * n })\nlet selected = filter(squares, fn(n) { return n > 10 })\nlet sum = reduce(selected, 0, fn(a, b) { return a + b })\nprint(selected, sum)', output: '[16, 25] 41\n', exercise: 'جمع مربع عددهای زوج را حساب کن.' },
  { id: 'json', title: '۹. JSON و متن', explanation: 'برای آکولاد واقعی در رشته از {{ و }} استفاده کن؛ {expression} برای درج مقدار است. JSON به آرایه یا دیکشنری زبان تبدیل می‌شود.', source: 'let user = json_parse(\'{{"name":"AION","level":2}}\')\nprint(user.name, user.level)\nprint(upper("aion"))', output: 'AION 2\nAION\n', exercise: 'level را زیاد کن و با json_stringify دوباره JSON تولید کن.' },
  { id: 'testing', title: '۱۰. تست قابل اجرا', explanation: 'assert اگر شرط false باشد خطا می‌دهد. فرمان test توابعی را اجرا می‌کند که نامشان با test_ شروع می‌شود.', source: 'fn square(n: Int) -> Int { return n * n }\nfn test_square() { assert(square(7) == 49) }\ntest_square()\nprint("تست موفق")', output: 'تست موفق\n', exercise: 'یک assert اشتباه بنویس و پیام E_ASSERT را بررسی کن.' }
];
