import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { buildFile, runBundle, validateBundle, createFileHost } from './modules.mjs';
import { compile } from './api.mjs';
function fixture(files){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aion-test-'));for(const[name,source]of Object.entries(files)){fs.mkdirSync(path.dirname(path.join(dir,name)),{recursive:true});fs.writeFileSync(path.join(dir,name),source);}return dir;}
function clean(dir){assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep+'aion-test-'));fs.rmSync(dir,{recursive:true,force:true});}
test('imports execute once and retain isolated module globals',()=>{const dir=fixture({'main.ai':'import { next } from "./lib.ai" print(next(),next())','lib.ai':'var n=5 export fn next() { n+=1 return n }'});try{assert.equal(runBundle(buildFile(path.join(dir,'main.ai'))).output,'6 7\n');}finally{clean(dir);}});
test('build artifacts survive JSON serialization and preserve closures',()=>{const dir=fixture({'main.ai':'fn make(n) { return fn(x) { return n+x } } print(make(3)(5))'});try{const bundle=JSON.parse(JSON.stringify(buildFile(path.join(dir,'main.ai'))));assert.equal(runBundle(bundle).output,'8\n');}finally{clean(dir);}});
test('imported typed functions reject bad calls',()=>{const dir=fixture({'main.ai':'import { double } from "./lib.ai" print(double("x"))','lib.ai':'export fn double(n: Int) -> Int { return n*2 }'});try{assert.throws(()=>buildFile(path.join(dir,'main.ai')),/Int.*String/);}finally{clean(dir);}});
test('missing exports rejected',()=>{const dir=fixture({'main.ai':'import { hidden } from "./lib.ai"','lib.ai':'fn hidden() {}'});try{assert.throws(()=>buildFile(path.join(dir,'main.ai')),/not exported/);}finally{clean(dir);}});
test('cyclic imports rejected with module diagnostic',()=>{const dir=fixture({'main.ai':'import { b } from "./lib.ai" export let a=1','lib.ai':'import { a } from "./main.ai" export let b=2'});try{assert.throws(()=>buildFile(path.join(dir,'main.ai')),/cycle/i);}finally{clean(dir);}});
test('imports cannot escape project root',()=>{const dir=fixture({'main.ai':'import { x } from "../outside.ai"'});try{assert.throws(()=>buildFile(path.join(dir,'main.ai')),/root|resolve/);}finally{clean(dir);}});
test('unknown artifact format rejected',()=>assert.throws(()=>validateBundle({format:'other',modules:[]}),/bytecode|bundle/i));
test('unknown opcodes and jump destinations rejected before execution',()=>{const module=compile('print(1)');let bundle={format:'aion.bundle',version:1,entry:'main.ai',modules:[{id:'main.ai',module,dependencies:{}}]};module.functions[0].code[0]=['EVIL'];assert.throws(()=>validateBundle(bundle),/opcode/i);module.functions[0].code[0]=['JUMP',9999];assert.throws(()=>validateBundle(bundle),/jump/i);});
test('file access denied without explicit capability',()=>{const dir=fixture({'main.ai':'print(read_text("secret.txt"))','secret.txt':'private'});try{assert.throws(()=>runBundle(buildFile(path.join(dir,'main.ai'))),e=>e.code==='E_CAPABILITY');}finally{clean(dir);}});
test('read capability confines real paths and rejects traversal',()=>{const dir=fixture({'main.ai':'print(read_text("allowed/data.txt"))','allowed/data.txt':'hello'});try{const host=createFileHost({base:dir,read:[path.join(dir,'allowed')]});assert.equal(runBundle(buildFile(path.join(dir,'main.ai')),{host}).output,'hello\n');assert.throws(()=>host.readText('../outside.txt'),/capability|scope|resolve/i);}finally{clean(dir);}});
test('write capability confines targets',()=>{const dir=fixture({'main.ai':'write_text("out/result.txt", "done")','out/.keep':''});try{const host=createFileHost({base:dir,write:[path.join(dir,'out')]});runBundle(buildFile(path.join(dir,'main.ai')),{host});assert.equal(fs.readFileSync(path.join(dir,'out/result.txt'),'utf8'),'done');assert.throws(()=>host.writeText('main.ai','overwrite'),/scope|capability/i);}finally{clean(dir);}});
