import {lessons} from './lessons.mjs';
const source=document.querySelector('#source'),status=document.querySelector('#status'),output=document.querySelector('#output');
let current=lessons[0],worker=null,timer=null,completed=new Set();
try{completed=new Set(JSON.parse(localStorage.getItem('aion-lessons')??'[]'));}catch{}
const progress=()=>document.querySelector('#progress').textContent=`پیشرفت: ${lessons.filter(l=>completed.has(l.id)).length} از ${lessons.length} درس اجرا شده است. میان‌بر اجرا: Ctrl + Enter`;
function select(lesson){worker?.terminate();clearTimeout(timer);current=lesson;source.value=lesson.source;document.querySelector('#title').textContent=lesson.title;document.querySelector('#description').textContent=lesson.explanation;document.querySelector('#exercise').textContent=lesson.exercise;document.querySelector('#expected').textContent=lesson.output;output.textContent='خروجی اینجا نمایش داده می‌شود.';status.textContent='آماده';for(const button of document.querySelectorAll('#chapters button'))button.setAttribute('aria-current',String(button.dataset.lesson===lesson.id));}
for(const lesson of lessons){const button=document.createElement('button');button.textContent=lesson.title;button.dataset.lesson=lesson.id;button.onclick=()=>select(lesson);document.querySelector('#chapters').append(button);}
function run(){worker?.terminate();clearTimeout(timer);status.textContent='در حال اجرا…';const original=source.value,lesson=current;worker=new Worker('./playground-worker.mjs',{type:'module'});worker.onmessage=({data})=>{clearTimeout(timer);output.textContent=data.text||'(بدون خروجی)';status.textContent=data.ok?'اجرا موفق بود':'کد را بررسی کن';if(data.ok&&original===lesson.source&&data.text===lesson.output){completed.add(lesson.id);try{localStorage.setItem('aion-lessons',JSON.stringify([...completed]));}catch{}progress();}worker.terminate();};worker.onerror=()=>{clearTimeout(timer);status.textContent='خطا';output.textContent='صفحه را از سرور محلی node serve.mjs باز کن.';};worker.postMessage({action:'run',source:original,lang:'fa'});timer=setTimeout(()=>{worker.terminate();status.textContent='توقف';output.textContent='زمان اجرای مرورگر بیش از پنج ثانیه شد.';},5000);}
document.querySelector('#run').onclick=run;source.onkeydown=e=>{if(e.ctrlKey&&e.key==='Enter'){e.preventDefault();run();}if(e.key==='Tab'){e.preventDefault();source.setRangeText('  ',source.selectionStart,source.selectionEnd,'end');}};select(current);progress();
